import type { TerminalTheme } from './types';

export const TERMINAL_THEMES: TerminalTheme[] = [
  {
    id: 'homebrew',
    name: 'Homebrew',
    description: 'Classic green-on-black',
    background: '#000000',
    foreground: '#00ff00',
    cursor: '#00ff00',
    cursorAccent: '#000000',
    selectionBackground: '#00ff0030',
    black: '#000000',
    red: '#c23621',
    green: '#25bc24',
    yellow: '#adad27',
    blue: '#492ee1',
    magenta: '#d338d3',
    cyan: '#33bbc8',
    white: '#cbcccd',
    brightBlack: '#818383',
    brightRed: '#fc391f',
    brightGreen: '#31e722',
    brightYellow: '#eaec23',
    brightBlue: '#5833ff',
    brightMagenta: '#f935f8',
    brightCyan: '#14f0f0',
    brightWhite: '#e9ebeb',
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    description: "GitHub's dark mode palette",
    background: '#0d1117',
    foreground: '#c9d1d9',
    cursor: '#58a6ff',
    cursorAccent: '#0d1117',
    selectionBackground: '#1f3553',
    black: '#484f58',
    red: '#ff7b72',
    green: '#3fb950',
    yellow: '#d29922',
    blue: '#58a6ff',
    magenta: '#bc8cff',
    cyan: '#39c5cf',
    white: '#b1bac4',
    brightBlack: '#6e7681',
    brightRed: '#ffa198',
    brightGreen: '#56d364',
    brightYellow: '#e3b341',
    brightBlue: '#79c0ff',
    brightMagenta: '#d2a8ff',
    brightCyan: '#56d4dd',
    brightWhite: '#f0f6fc',
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: 'Dark with vibrant purple accents',
    background: '#282a36',
    foreground: '#f8f8f2',
    cursor: '#f8f8f2',
    cursorAccent: '#282a36',
    selectionBackground: '#44475a',
    black: '#21222c',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#bd93f9',
    magenta: '#ff79c6',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff',
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    description: 'Precision colors by Ethan Schoonover',
    background: '#002b36',
    foreground: '#839496',
    cursor: '#268bd2',
    cursorAccent: '#002b36',
    selectionBackground: '#073642',
    black: '#073642',
    red: '#dc322f',
    green: '#859900',
    yellow: '#b58900',
    blue: '#268bd2',
    magenta: '#d33682',
    cyan: '#2aa198',
    white: '#eee8d5',
    brightBlack: '#002b36',
    brightRed: '#cb4b16',
    brightGreen: '#586e75',
    brightYellow: '#657b83',
    brightBlue: '#839496',
    brightMagenta: '#6c71c4',
    brightCyan: '#93a1a1',
    brightWhite: '#fdf6e3',
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    description: "Atom's iconic dark theme",
    background: '#282c34',
    foreground: '#abb2bf',
    cursor: '#528bff',
    cursorAccent: '#282c34',
    selectionBackground: '#3e4451',
    black: '#3f4451',
    red: '#e06c75',
    green: '#98c379',
    yellow: '#e5c07b',
    blue: '#61afef',
    magenta: '#c678dd',
    cyan: '#56b6c2',
    white: '#abb2bf',
    brightBlack: '#4f5666',
    brightRed: '#ff616e',
    brightGreen: '#a5e075',
    brightYellow: '#f0a45d',
    brightBlue: '#4dc4ff',
    brightMagenta: '#de73ff',
    brightCyan: '#4cd1e0',
    brightWhite: '#ffffff',
  },
  {
    id: 'monokai',
    name: 'Monokai',
    description: 'Timeless Sublime Text palette',
    background: '#1e1e1e',
    foreground: '#f8f8f2',
    cursor: '#f8f8f0',
    cursorAccent: '#1e1e1e',
    selectionBackground: '#49483e',
    black: '#272822',
    red: '#f92672',
    green: '#a6e22e',
    yellow: '#f4bf75',
    blue: '#66d9e8',
    magenta: '#ae81ff',
    cyan: '#a1efe4',
    white: '#f8f8f2',
    brightBlack: '#75715e',
    brightRed: '#f92672',
    brightGreen: '#a6e22e',
    brightYellow: '#f4bf75',
    brightBlue: '#66d9e8',
    brightMagenta: '#ae81ff',
    brightCyan: '#a1efe4',
    brightWhite: '#f9f8f5',
  },
  {
    id: 'nord',
    name: 'Nord',
    description: 'Arctic north-bluish palette',
    background: '#2e3440',
    foreground: '#d8dee9',
    cursor: '#88c0d0',
    cursorAccent: '#2e3440',
    selectionBackground: '#434c5e',
    black: '#3b4252',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
    blue: '#81a1c1',
    magenta: '#b48ead',
    cyan: '#88c0d0',
    white: '#e5e9f0',
    brightBlack: '#4c566a',
    brightRed: '#bf616a',
    brightGreen: '#a3be8c',
    brightYellow: '#ebcb8b',
    brightBlue: '#81a1c1',
    brightMagenta: '#b48ead',
    brightCyan: '#8fbcbb',
    brightWhite: '#eceff4',
  },
];

export const DEFAULT_THEME_ID = 'homebrew';
export const THEME_KEY = 'i2c-terminal-theme';

export function getThemeById(id: string): TerminalTheme {
  return TERMINAL_THEMES.find((t) => t.id === id) || TERMINAL_THEMES[0];
}

export function loadThemeId(): string {
  try {
    return localStorage.getItem(THEME_KEY) || DEFAULT_THEME_ID;
  } catch {
    return DEFAULT_THEME_ID;
  }
}

export function saveThemeId(id: string) {
  try {
    localStorage.setItem(THEME_KEY, id);
  } catch {}
}

export function xtermTheme(t: TerminalTheme) {
  return {
    background: t.background,
    foreground: t.foreground,
    cursor: t.cursor,
    cursorAccent: t.cursorAccent,
    selectionBackground: t.selectionBackground,
    black: t.black,
    red: t.red,
    green: t.green,
    yellow: t.yellow,
    blue: t.blue,
    magenta: t.magenta,
    cyan: t.cyan,
    white: t.white,
    brightBlack: t.brightBlack,
    brightRed: t.brightRed,
    brightGreen: t.brightGreen,
    brightYellow: t.brightYellow,
    brightBlue: t.brightBlue,
    brightMagenta: t.brightMagenta,
    brightCyan: t.brightCyan,
    brightWhite: t.brightWhite,
  };
}
